export const SYNC_FUNCTION_TEMPLATE = `\
import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const GALYA_BASE = "https://api.galya.io/v1";
const GALYA_API_KEY = Deno.env.get("GALYA_API_KEY") ?? "";
const GALYA_WORKSPACE_ID = Deno.env.get("GALYA_WORKSPACE_ID") ?? "";

type ChangeEvent = {
  type: "INSERT" | "UPDATE" | "DELETE";
  record: Record<string, unknown> | null;
  old_record: Record<string, unknown> | null;
};

function galyaHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    "X-API-Key": GALYA_API_KEY,
    "Content-Type": "application/json",
  };
  if (GALYA_WORKSPACE_ID) {
    headers["X-Galya-Workspace-Id"] = GALYA_WORKSPACE_ID;
  }
  return headers;
}

async function indexRecord(record: Record<string, unknown>): Promise<void> {
  const url = String(record["__FIELD_URL__"] ?? "");
  __TITLE_EXTRACTION__
  __DESC_EXTRACTION__
  const content = [title, description].filter(Boolean).join(". ").trim() || url;

  await fetch(\`\${GALYA_BASE}/index\`, {
    method: "POST",
    headers: galyaHeaders(),
    body: JSON.stringify({
      content: { url, type: "__CONTENT_TYPE__", content },
    }),
  });
}

async function deleteRecord(record: Record<string, unknown>): Promise<void> {
  const entityUrl = \`\${GALYA_BASE}/entity?url=\${encodeURIComponent(
    String(record["__FIELD_URL__"] ?? "")
  )}\`;
  await fetch(entityUrl, { method: "DELETE", headers: galyaHeaders() });
}

Deno.serve(async (req) => {
  try {
    const event = (await req.json()) as ChangeEvent;
    if (event.type === "DELETE") {
      if (event.old_record) await deleteRecord(event.old_record);
    } else {
      if (event.record) await indexRecord(event.record);
    }
    return Response.json({ ok: true });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return Response.json({ ok: false, error: message }, { status: 500 });
  }
});
`;

export const RERANK_FUNCTION_TEMPLATE = `\
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { withSupabase } from "jsr:@supabase/server@^1";

const GALYA_BASE = "https://api.galya.io/v1";

export default {
  fetch: withSupabase({ auth: ["publishable", "secret"] }, async (req, ctx) => {
    const { userId } = await req.json().catch(() => ({ userId: undefined }));
    if (!userId) {
      return Response.json({ error: "userId is required" }, { status: 400 });
    }

    const { data: rows, error } = await ctx.supabaseAdmin
      .from("__TABLE__")
      .select("__FIELD_ID__, __FIELD_URL____OPTIONAL_TITLE____OPTIONAL_DESC__");

    if (error) return Response.json({ step: "read_rows", error }, { status: 500 });
    if (!rows?.length) return Response.json({ error: "no rows found" }, { status: 404 });

    const candidates = rows.map((row) => ({
      url: String(row["__FIELD_URL__"] ?? ""),
      type: "__CONTENT_TYPE__",
      content: [row["__FIELD_TITLE__"], row["__FIELD_DESC__"]]
        .filter(Boolean)
        .join(". ")
        .trim() || String(row["__FIELD_URL__"] ?? ""),
    }));

    const url = new URL(\`\${GALYA_BASE}/rerank\`);
    url.searchParams.set("relative_to_entity_id", userId);
    url.searchParams.set("in_terms_of_entity_type", "content");

    const galyaRes = await fetch(url, {
      method: "POST",
      headers: {
        "X-API-Key": Deno.env.get("GALYA_API_KEY") ?? "",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ candidates }),
    });

    if (!galyaRes.ok) {
      const detail = await galyaRes.text();
      return Response.json(
        { step: "galya_rerank", status: galyaRes.status, detail },
        { status: 502 }
      );
    }

    const reranked = await galyaRes.json();
    const rowByUrl = new Map(
      rows.map((row) => [String(row["__FIELD_URL__"] ?? ""), row])
    );
    const rankedRows = (reranked.results ?? [])
      .map((result: { url?: string }) =>
        result.url ? (rowByUrl.get(result.url) ?? null) : null
      )
      .filter(Boolean);

    return Response.json({ ranked_rows: rankedRows });
  }),
};
`;

export const TRIGGER_SQL_TEMPLATE = `\
-- Generated by @galya/supabase-sync
-- Fires galya-sync-__TABLE__ Edge Function on every INSERT, UPDATE, DELETE
--
-- WARNING: This file contains your Supabase service role key.
-- Add this file to your .gitignore before committing to version control.

CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

CREATE OR REPLACE FUNCTION galya_sync___TABLE__()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  payload jsonb;
BEGIN
  IF TG_OP = 'DELETE' THEN
    payload = jsonb_build_object(
      'type',       TG_OP,
      'record',     null,
      'old_record', row_to_json(OLD)
    );
  ELSE
    payload = jsonb_build_object(
      'type',       TG_OP,
      'record',     row_to_json(NEW),
      'old_record', null
    );
  END IF;

  PERFORM extensions.net.http_post(
    url     := '__PROJECT_URL__/functions/v1/galya-sync-__TABLE__',
    body    := payload,
    headers := jsonb_build_object(
      'Content-Type',  'application/json',
      'Authorization', 'Bearer __SERVICE_ROLE_KEY__'
    )
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS galya_sync___TABLE___trigger ON __TABLE__;

CREATE TRIGGER galya_sync___TABLE___trigger
  AFTER INSERT OR UPDATE OR DELETE ON __TABLE__
  FOR EACH ROW EXECUTE FUNCTION galya_sync___TABLE__();
`;
